import { useState } from 'react';
import { ShieldAlert, ExternalLink, Copy, CheckCircle } from 'lucide-react';
import type { ScanResult } from '../types';

export function CybercrimeAction({ result }: { result: ScanResult }) {
  const [copied, setCopied] = useState(false);

  const reportText = `DEEPSHIELD AI THREAT REPORT
Generated: ${new Date().toLocaleString()}
Scan Type: ${result.type}
Verdict: ${result.verdict}
Confidence: ${result.confidence}%
Trust Score: ${result.trust_score ?? 'N/A'}/100
Threat Level: ${result.threat_level}
Red Flags Found:
${result.red_flags.map(f => `- ${f}`).join('\n')}

Recommended Action: Report immediately to
National Cybercrime Portal: cybercrime.gov.in
Helpline: 1930

Generated by DeepShield AI | Team Easycoder`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-red-500/10 border border-red-200 dark:bg-red-950/30 dark:border-red-900/50 rounded-xl p-5">
      <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between mb-4">
        <div>
          <h4 className="text-red-600 dark:text-red-400 font-bold flex items-center gap-2 text-lg">
            <ShieldAlert className="w-5 h-5" /> Threat Action Required
          </h4>
          <p className="text-slate-400 text-sm mt-1">Please report this incident to authorities.</p>
        </div>
        <a
          href="https://cybercrime.gov.in"
          target="_blank"
          rel="noopener noreferrer"
          className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-bold flex items-center gap-2 transition-colors whitespace-nowrap shadow-[0_0_15px_rgba(239,68,68,0.3)]"
        >
          <ExternalLink className="w-4 h-4" /> 🚔 Report to Cybercrime
        </a>
      </div>
      <div className="bg-slate-950/50 rounded-lg border border-slate-800 p-3 relative group">
        <textarea
          readOnly
          value={reportText}
          className="w-full bg-transparent text-slate-400 text-xs font-mono resize-none outline-none custom-scrollbar h-32"
        />
        <button
          onClick={handleCopy}
          className="absolute top-3 right-3 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-slate-100 p-2 rounded flex items-center gap-2 transition-colors"
        >
          {copied ? <CheckCircle className="w-4 h-4 text-green-600 dark:text-green-400" /> : <Copy className="w-4 h-4" />}
          <span className="text-xs font-bold">{copied ? 'COPIED' : 'COPY REPORT'}</span>
        </button>
      </div>
    </div>
  );
}
